traefik:
  additionalArguments:
    - --providers.file.filename=/data/traefik-config.yaml
    - --entrypoints.websecure.http.tls.certresolver=cloudflare
    - --entrypoints.websecure.http.tls.domains[0].main=test.livepeer.fish
    - --entrypoints.websecure.http.tls.domains[0].sans=*.test.livepeer.fish
    - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
    - --certificatesresolvers.cloudflare.acme.email=dane@livepeer.org
    - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
    - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
  ports:
    web:
      redirectTo: websecure
  env:
    - name: CF_DNS_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: zone_token
          name: cloudflare-api-credentials
    - name: CF_ZONE_API_TOKEN
      valueFrom:
        secretKeyRef:
          key: dns_token
          name: cloudflare-api-credentials
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  persistence:
    enabled: true
    path: /certs
    size: 128Mi
  volumes:
    - mountPath: /data
      name: traefik-config
      type: configMap
