apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "sthc.fullname" . }}
  labels:
    {{- include "sthc.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: test.livepeer.fish
spec:
  rules:
  - host: "sthc.test.livepeer.fish"
    http:
      paths:
      - path: /
        backend:
          serviceName: sthc
          servicePort: 80
