apiVersion: v2
name: monitoring
description: |
  resources to surface metrics from the test cluster
type: application
version: 0.2.0
appVersion: 1.0.0
# dependencies:
# - name: prometheus
#   version: "12.0.1"
#   repository: "https://prometheus-community.github.io/helm-charts"
