kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-metabase
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    org.metabase.instance: {{ .Release.Name }}-metabase
  ports:
  - targetPort: 3000
    port: 3000
    name: app
  type: {{ .Values.general.serviceType }}
